# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentTwinControlRoute(BaseModel):
    """
    A user-facing route derived from existing twin controls.
    """ # noqa: E501
    id: StrictStr
    label: StrictStr
    route_kind: StrictStr
    input_kinds: Optional[List[StrictStr]] = None
    output_action_kind: StrictStr
    readiness: StrictStr
    reason: Optional[StrictStr] = None
    missing_capabilities: Optional[List[StrictStr]] = None
    requires_confirmation: Optional[StrictBool] = True
    priority: Optional[StrictInt] = 100
    operator_label: Optional[StrictStr] = None
    operator_description: Optional[StrictStr] = None
    developer_label: Optional[StrictStr] = None
    setup_hint: Optional[StrictStr] = None
    setup_target: Optional[StrictStr] = None
    resolver_metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "label", "route_kind", "input_kinds", "output_action_kind", "readiness", "reason", "missing_capabilities", "requires_confirmation", "priority", "operator_label", "operator_description", "developer_label", "setup_hint", "setup_target", "resolver_metadata"]

    @field_validator('output_action_kind')
    def output_action_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['navigation_command', 'controller_policy_execute', 'observe_latest_frame', 'stop_navigation', 'twin_motion_action', 'joint_control', 'movement_plan_from_prompt', 'end_effector_target']):
            raise ValueError("must be one of enum values ('navigation_command', 'controller_policy_execute', 'observe_latest_frame', 'stop_navigation', 'twin_motion_action', 'joint_control', 'movement_plan_from_prompt', 'end_effector_target')")
        return value

    @field_validator('readiness')
    def readiness_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ready', 'needs_setup', 'preview_only', 'unavailable']):
            raise ValueError("must be one of enum values ('ready', 'needs_setup', 'preview_only', 'unavailable')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentTwinControlRoute from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if operator_label (nullable) is None
        # and model_fields_set contains the field
        if self.operator_label is None and "operator_label" in self.model_fields_set:
            _dict['operator_label'] = None

        # set to None if operator_description (nullable) is None
        # and model_fields_set contains the field
        if self.operator_description is None and "operator_description" in self.model_fields_set:
            _dict['operator_description'] = None

        # set to None if developer_label (nullable) is None
        # and model_fields_set contains the field
        if self.developer_label is None and "developer_label" in self.model_fields_set:
            _dict['developer_label'] = None

        # set to None if setup_hint (nullable) is None
        # and model_fields_set contains the field
        if self.setup_hint is None and "setup_hint" in self.model_fields_set:
            _dict['setup_hint'] = None

        # set to None if setup_target (nullable) is None
        # and model_fields_set contains the field
        if self.setup_target is None and "setup_target" in self.model_fields_set:
            _dict['setup_target'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentTwinControlRoute from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "label": obj.get("label"),
            "route_kind": obj.get("route_kind"),
            "input_kinds": obj.get("input_kinds"),
            "output_action_kind": obj.get("output_action_kind"),
            "readiness": obj.get("readiness"),
            "reason": obj.get("reason"),
            "missing_capabilities": obj.get("missing_capabilities"),
            "requires_confirmation": obj.get("requires_confirmation") if obj.get("requires_confirmation") is not None else True,
            "priority": obj.get("priority") if obj.get("priority") is not None else 100,
            "operator_label": obj.get("operator_label"),
            "operator_description": obj.get("operator_description"),
            "developer_label": obj.get("developer_label"),
            "setup_hint": obj.get("setup_hint"),
            "setup_target": obj.get("setup_target"),
            "resolver_metadata": obj.get("resolver_metadata")
        })
        return _obj


