# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cyberwave.rest.models.agent_controller_runtime_route_ref_schema import AgentControllerRuntimeRouteRefSchema
from cyberwave.rest.models.agent_twin_control_joint_schema import AgentTwinControlJointSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentTwinControl(BaseModel):
    """
    A single existing control API affordance for a twin.
    """ # noqa: E501
    kind: StrictStr
    label: StrictStr
    available: StrictBool
    dispatchability: StrictStr
    execution_channel: StrictStr
    transport: StrictStr
    requires_confirmation: Optional[StrictBool] = True
    reason: Optional[StrictStr] = None
    source_types: Optional[List[StrictStr]] = None
    commands: Optional[List[StrictStr]] = None
    controller_policy_uuids: Optional[List[StrictStr]] = None
    controller_policy_defaults: Optional[Dict[str, Dict[str, AgentControllerRuntimeRouteRefSchema]]] = None
    asset_uuid: Optional[StrictStr] = None
    end_effector_frame: Optional[StrictStr] = None
    missing_capabilities: Optional[List[StrictStr]] = None
    sensor_ids: Optional[List[StrictStr]] = None
    sensor_geometries: Optional[List[Optional[Dict[str, Any]]]] = None
    poses: Optional[List[Dict[str, StrictStr]]] = None
    movements: Optional[List[Dict[str, StrictStr]]] = None
    joints: Optional[List[AgentTwinControlJointSchema]] = None
    preview_available: Optional[StrictBool] = None
    execution_available: Optional[StrictBool] = None
    readiness: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["kind", "label", "available", "dispatchability", "execution_channel", "transport", "requires_confirmation", "reason", "source_types", "commands", "controller_policy_uuids", "controller_policy_defaults", "asset_uuid", "end_effector_frame", "missing_capabilities", "sensor_ids", "sensor_geometries", "poses", "movements", "joints", "preview_available", "execution_available", "readiness"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['navigation_command', 'controller_policy_execute', 'observe_latest_frame', 'stop_navigation', 'twin_motion_action', 'joint_control', 'movement_plan_from_prompt', 'end_effector_target']):
            raise ValueError("must be one of enum values ('navigation_command', 'controller_policy_execute', 'observe_latest_frame', 'stop_navigation', 'twin_motion_action', 'joint_control', 'movement_plan_from_prompt', 'end_effector_target')")
        return value

    @field_validator('readiness')
    def readiness_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ready', 'needs_setup', 'preview_only', 'unavailable']):
            raise ValueError("must be one of enum values ('ready', 'needs_setup', 'preview_only', 'unavailable')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentTwinControl from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in controller_policy_defaults (dict of dict)
        _field_dict_of_dict = {}
        if self.controller_policy_defaults:
            for _key_controller_policy_defaults, _value_controller_policy_defaults in self.controller_policy_defaults.items():
                if _value_controller_policy_defaults is not None:
                    _field_dict_of_dict[_key_controller_policy_defaults] = {
                        _key: _value.to_dict() for _key, _value in _value_controller_policy_defaults.items()
                    }
            _dict['controller_policy_defaults'] = _field_dict_of_dict
        # override the default output from pydantic by calling `to_dict()` of each item in joints (list)
        _items = []
        if self.joints:
            for _item_joints in self.joints:
                if _item_joints:
                    _items.append(_item_joints.to_dict())
            _dict['joints'] = _items
        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if asset_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.asset_uuid is None and "asset_uuid" in self.model_fields_set:
            _dict['asset_uuid'] = None

        # set to None if end_effector_frame (nullable) is None
        # and model_fields_set contains the field
        if self.end_effector_frame is None and "end_effector_frame" in self.model_fields_set:
            _dict['end_effector_frame'] = None

        # set to None if preview_available (nullable) is None
        # and model_fields_set contains the field
        if self.preview_available is None and "preview_available" in self.model_fields_set:
            _dict['preview_available'] = None

        # set to None if execution_available (nullable) is None
        # and model_fields_set contains the field
        if self.execution_available is None and "execution_available" in self.model_fields_set:
            _dict['execution_available'] = None

        # set to None if readiness (nullable) is None
        # and model_fields_set contains the field
        if self.readiness is None and "readiness" in self.model_fields_set:
            _dict['readiness'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentTwinControl from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "label": obj.get("label"),
            "available": obj.get("available"),
            "dispatchability": obj.get("dispatchability"),
            "execution_channel": obj.get("execution_channel"),
            "transport": obj.get("transport"),
            "requires_confirmation": obj.get("requires_confirmation") if obj.get("requires_confirmation") is not None else True,
            "reason": obj.get("reason"),
            "source_types": obj.get("source_types"),
            "commands": obj.get("commands"),
            "controller_policy_uuids": obj.get("controller_policy_uuids"),
            "controller_policy_defaults": dict(
                (_k, dict(
                    (_ik, AgentControllerRuntimeRouteRefSchema.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj["controller_policy_defaults"].items()
            )
            if obj.get("controller_policy_defaults") is not None
            else None,
            "asset_uuid": obj.get("asset_uuid"),
            "end_effector_frame": obj.get("end_effector_frame"),
            "missing_capabilities": obj.get("missing_capabilities"),
            "sensor_ids": obj.get("sensor_ids"),
            "sensor_geometries": obj.get("sensor_geometries"),
            "poses": obj.get("poses"),
            "movements": obj.get("movements"),
            "joints": [AgentTwinControlJointSchema.from_dict(_item) for _item in obj["joints"]] if obj.get("joints") is not None else None,
            "preview_available": obj.get("preview_available"),
            "execution_available": obj.get("execution_available"),
            "readiness": obj.get("readiness")
        })
        return _obj


