# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentControlAction(BaseModel):
    """
    Existing Cyberwave API call proposed by the control planner.
    """ # noqa: E501
    kind: StrictStr
    dispatchability: Optional[StrictStr] = 'dispatchable'
    transport: Optional[StrictStr] = None
    target_twin_uuid: StrictStr
    payload: Optional[Dict[str, Any]] = None
    requires_confirmation: Optional[StrictBool] = True
    controller_policy_uuid: Optional[StrictStr] = None
    asset_uuid: Optional[StrictStr] = None
    trajectory_preview: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["kind", "dispatchability", "transport", "target_twin_uuid", "payload", "requires_confirmation", "controller_policy_uuid", "asset_uuid", "trajectory_preview"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['navigation_command', 'controller_policy_execute', 'observe_latest_frame', 'stop_navigation', 'twin_motion_action', 'joint_control', 'movement_plan_from_prompt', 'end_effector_target']):
            raise ValueError("must be one of enum values ('navigation_command', 'controller_policy_execute', 'observe_latest_frame', 'stop_navigation', 'twin_motion_action', 'joint_control', 'movement_plan_from_prompt', 'end_effector_target')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentControlAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if transport (nullable) is None
        # and model_fields_set contains the field
        if self.transport is None and "transport" in self.model_fields_set:
            _dict['transport'] = None

        # set to None if controller_policy_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.controller_policy_uuid is None and "controller_policy_uuid" in self.model_fields_set:
            _dict['controller_policy_uuid'] = None

        # set to None if asset_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.asset_uuid is None and "asset_uuid" in self.model_fields_set:
            _dict['asset_uuid'] = None

        # set to None if trajectory_preview (nullable) is None
        # and model_fields_set contains the field
        if self.trajectory_preview is None and "trajectory_preview" in self.model_fields_set:
            _dict['trajectory_preview'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentControlAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "dispatchability": obj.get("dispatchability") if obj.get("dispatchability") is not None else 'dispatchable',
            "transport": obj.get("transport"),
            "target_twin_uuid": obj.get("target_twin_uuid"),
            "payload": obj.get("payload"),
            "requires_confirmation": obj.get("requires_confirmation") if obj.get("requires_confirmation") is not None else True,
            "controller_policy_uuid": obj.get("controller_policy_uuid"),
            "asset_uuid": obj.get("asset_uuid"),
            "trajectory_preview": obj.get("trajectory_preview")
        })
        return _obj


