# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentControlRouteResolveRequest(BaseModel):
    """
    Normalize a route id plus user inputs into a plan.  \"Resolve\" here means deterministic backend normalization of a user-facing route and small input dict into the canonical Control Assistant action contract. ``prompt_motion_mlmodel_uuid`` is a user override; backend defaults apply when omitted.
    """ # noqa: E501
    route_id: StrictStr
    inputs: Optional[Dict[str, Any]] = None
    summary: Optional[StrictStr] = 'Resolved control route.'
    target_twin_uuid: Optional[StrictStr] = None
    twin_uuid: Optional[StrictStr] = None
    mode: Optional[StrictStr] = 'simulation'
    simulation_backend: Optional[StrictStr] = None
    perception_evidence: Optional[Dict[str, Any]] = None
    prompt_motion_mlmodel_uuid: Optional[StrictStr] = None
    requires_confirmation: Optional[StrictBool] = None
    current_joint_states: Optional[Dict[str, Any]] = None
    current_sensor_states: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["route_id", "inputs", "summary", "target_twin_uuid", "twin_uuid", "mode", "simulation_backend", "perception_evidence", "prompt_motion_mlmodel_uuid", "requires_confirmation", "current_joint_states", "current_sensor_states"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['simulation', 'live', 'preview']):
            raise ValueError("must be one of enum values ('simulation', 'live', 'preview')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentControlRouteResolveRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if target_twin_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.target_twin_uuid is None and "target_twin_uuid" in self.model_fields_set:
            _dict['target_twin_uuid'] = None

        # set to None if twin_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.twin_uuid is None and "twin_uuid" in self.model_fields_set:
            _dict['twin_uuid'] = None

        # set to None if simulation_backend (nullable) is None
        # and model_fields_set contains the field
        if self.simulation_backend is None and "simulation_backend" in self.model_fields_set:
            _dict['simulation_backend'] = None

        # set to None if perception_evidence (nullable) is None
        # and model_fields_set contains the field
        if self.perception_evidence is None and "perception_evidence" in self.model_fields_set:
            _dict['perception_evidence'] = None

        # set to None if prompt_motion_mlmodel_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_motion_mlmodel_uuid is None and "prompt_motion_mlmodel_uuid" in self.model_fields_set:
            _dict['prompt_motion_mlmodel_uuid'] = None

        # set to None if requires_confirmation (nullable) is None
        # and model_fields_set contains the field
        if self.requires_confirmation is None and "requires_confirmation" in self.model_fields_set:
            _dict['requires_confirmation'] = None

        # set to None if current_joint_states (nullable) is None
        # and model_fields_set contains the field
        if self.current_joint_states is None and "current_joint_states" in self.model_fields_set:
            _dict['current_joint_states'] = None

        # set to None if current_sensor_states (nullable) is None
        # and model_fields_set contains the field
        if self.current_sensor_states is None and "current_sensor_states" in self.model_fields_set:
            _dict['current_sensor_states'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentControlRouteResolveRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "route_id": obj.get("route_id"),
            "inputs": obj.get("inputs"),
            "summary": obj.get("summary") if obj.get("summary") is not None else 'Resolved control route.',
            "target_twin_uuid": obj.get("target_twin_uuid"),
            "twin_uuid": obj.get("twin_uuid"),
            "mode": obj.get("mode") if obj.get("mode") is not None else 'simulation',
            "simulation_backend": obj.get("simulation_backend"),
            "perception_evidence": obj.get("perception_evidence"),
            "prompt_motion_mlmodel_uuid": obj.get("prompt_motion_mlmodel_uuid"),
            "requires_confirmation": obj.get("requires_confirmation"),
            "current_joint_states": obj.get("current_joint_states"),
            "current_sensor_states": obj.get("current_sensor_states")
        })
        return _obj


