# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentEmbodimentContextSchema(BaseModel):
    """
    Server-built embodiment context surfaced to the client for debugging.
    """ # noqa: E501
    environment_uuid: StrictStr
    twin_uuid: Optional[StrictStr] = None
    asset_uuid: Optional[StrictStr] = None
    controller_policy_uuid: Optional[StrictStr] = None
    mode: StrictStr
    simulation_backend: Optional[StrictStr] = None
    capabilities: Optional[Dict[str, Any]] = None
    waypoints: Optional[List[Optional[Dict[str, Any]]]] = None
    frames: Optional[List[Optional[Dict[str, Any]]]] = None
    notes: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["environment_uuid", "twin_uuid", "asset_uuid", "controller_policy_uuid", "mode", "simulation_backend", "capabilities", "waypoints", "frames", "notes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentEmbodimentContextSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if twin_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.twin_uuid is None and "twin_uuid" in self.model_fields_set:
            _dict['twin_uuid'] = None

        # set to None if asset_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.asset_uuid is None and "asset_uuid" in self.model_fields_set:
            _dict['asset_uuid'] = None

        # set to None if controller_policy_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.controller_policy_uuid is None and "controller_policy_uuid" in self.model_fields_set:
            _dict['controller_policy_uuid'] = None

        # set to None if simulation_backend (nullable) is None
        # and model_fields_set contains the field
        if self.simulation_backend is None and "simulation_backend" in self.model_fields_set:
            _dict['simulation_backend'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentEmbodimentContextSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "environment_uuid": obj.get("environment_uuid"),
            "twin_uuid": obj.get("twin_uuid"),
            "asset_uuid": obj.get("asset_uuid"),
            "controller_policy_uuid": obj.get("controller_policy_uuid"),
            "mode": obj.get("mode"),
            "simulation_backend": obj.get("simulation_backend"),
            "capabilities": obj.get("capabilities"),
            "waypoints": obj.get("waypoints"),
            "frames": obj.get("frames"),
            "notes": obj.get("notes")
        })
        return _obj


