# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from cyberwave.rest.models.agent_control_action_spec_schema import AgentControlActionSpecSchema
from cyberwave.rest.models.agent_control_perception_options_schema import AgentControlPerceptionOptionsSchema
from cyberwave.rest.models.agent_control_prompt_motion_options_schema import AgentControlPromptMotionOptionsSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentControlOptionsSchema(BaseModel):
    """
    Control Assistant option payload for lightweight helper UIs.
    """ # noqa: E501
    action_specs: Optional[List[AgentControlActionSpecSchema]] = None
    perception_evidence: AgentControlPerceptionOptionsSchema
    prompt_motion: AgentControlPromptMotionOptionsSchema
    __properties: ClassVar[List[str]] = ["action_specs", "perception_evidence", "prompt_motion"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentControlOptionsSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in action_specs (list)
        _items = []
        if self.action_specs:
            for _item_action_specs in self.action_specs:
                if _item_action_specs:
                    _items.append(_item_action_specs.to_dict())
            _dict['action_specs'] = _items
        # override the default output from pydantic by calling `to_dict()` of perception_evidence
        if self.perception_evidence:
            _dict['perception_evidence'] = self.perception_evidence.to_dict()
        # override the default output from pydantic by calling `to_dict()` of prompt_motion
        if self.prompt_motion:
            _dict['prompt_motion'] = self.prompt_motion.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentControlOptionsSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action_specs": [AgentControlActionSpecSchema.from_dict(_item) for _item in obj["action_specs"]] if obj.get("action_specs") is not None else None,
            "perception_evidence": AgentControlPerceptionOptionsSchema.from_dict(obj["perception_evidence"]) if obj.get("perception_evidence") is not None else None,
            "prompt_motion": AgentControlPromptMotionOptionsSchema.from_dict(obj["prompt_motion"]) if obj.get("prompt_motion") is not None else None
        })
        return _obj


