# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentControlEvidenceResolveRequest(BaseModel):
    """
    Already-available structured perception/scene result for target resolve.  Accepts either a flat payload or one wrapped under ``result``/``selected_result``/ ``detection``/``grasp`` (matches common perception model output shapes). The target must be in world frame; the field name encodes that — there is no separate ``frame`` or ``validated_world_target`` flag.
    """ # noqa: E501
    result: Optional[Dict[str, Any]] = None
    selected_result: Optional[Dict[str, Any]] = None
    detection: Optional[Dict[str, Any]] = None
    grasp: Optional[Dict[str, Any]] = None
    world_position: Optional[Any] = None
    quaternion: Optional[List[Union[StrictFloat, StrictInt]]] = None
    model_task_ref: Optional[StrictStr] = None
    mlmodel_uuid: Optional[StrictStr] = None
    mlmodel_run_uuid: Optional[StrictStr] = None
    frame_id: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    confidence: Optional[Union[StrictFloat, StrictInt]] = None
    metadata: Optional[Dict[str, Any]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["result", "selected_result", "detection", "grasp", "world_position", "quaternion", "model_task_ref", "mlmodel_uuid", "mlmodel_run_uuid", "frame_id", "label", "confidence", "metadata"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentControlEvidenceResolveRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if result (nullable) is None
        # and model_fields_set contains the field
        if self.result is None and "result" in self.model_fields_set:
            _dict['result'] = None

        # set to None if selected_result (nullable) is None
        # and model_fields_set contains the field
        if self.selected_result is None and "selected_result" in self.model_fields_set:
            _dict['selected_result'] = None

        # set to None if detection (nullable) is None
        # and model_fields_set contains the field
        if self.detection is None and "detection" in self.model_fields_set:
            _dict['detection'] = None

        # set to None if grasp (nullable) is None
        # and model_fields_set contains the field
        if self.grasp is None and "grasp" in self.model_fields_set:
            _dict['grasp'] = None

        # set to None if world_position (nullable) is None
        # and model_fields_set contains the field
        if self.world_position is None and "world_position" in self.model_fields_set:
            _dict['world_position'] = None

        # set to None if quaternion (nullable) is None
        # and model_fields_set contains the field
        if self.quaternion is None and "quaternion" in self.model_fields_set:
            _dict['quaternion'] = None

        # set to None if model_task_ref (nullable) is None
        # and model_fields_set contains the field
        if self.model_task_ref is None and "model_task_ref" in self.model_fields_set:
            _dict['model_task_ref'] = None

        # set to None if mlmodel_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.mlmodel_uuid is None and "mlmodel_uuid" in self.model_fields_set:
            _dict['mlmodel_uuid'] = None

        # set to None if mlmodel_run_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.mlmodel_run_uuid is None and "mlmodel_run_uuid" in self.model_fields_set:
            _dict['mlmodel_run_uuid'] = None

        # set to None if frame_id (nullable) is None
        # and model_fields_set contains the field
        if self.frame_id is None and "frame_id" in self.model_fields_set:
            _dict['frame_id'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if confidence (nullable) is None
        # and model_fields_set contains the field
        if self.confidence is None and "confidence" in self.model_fields_set:
            _dict['confidence'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentControlEvidenceResolveRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "result": obj.get("result"),
            "selected_result": obj.get("selected_result"),
            "detection": obj.get("detection"),
            "grasp": obj.get("grasp"),
            "world_position": obj.get("world_position"),
            "quaternion": obj.get("quaternion"),
            "model_task_ref": obj.get("model_task_ref"),
            "mlmodel_uuid": obj.get("mlmodel_uuid"),
            "mlmodel_run_uuid": obj.get("mlmodel_run_uuid"),
            "frame_id": obj.get("frame_id"),
            "label": obj.get("label"),
            "confidence": obj.get("confidence"),
            "metadata": obj.get("metadata")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


