# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyberwave.rest.models.ai_usage_cost_source_breakdown import AIUsageCostSourceBreakdown
from cyberwave.rest.models.ai_usage_day_bucket import AIUsageDayBucket
from cyberwave.rest.models.ai_usage_summary import AIUsageSummary
from cyberwave.rest.models.ai_usage_totals import AIUsageTotals
from cyberwave.rest.models.metrics_window_schema import MetricsWindowSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AIMetricsSchema(BaseModel):
    """
    Workspace-scoped LLM / embedding / image usage roll-up.  Mirrors :class:`EventMetricsSchema` in shape (workspace + window + grouped summaries + per-day series) so frontend chart code can reuse the same scaffolding.
    """ # noqa: E501
    workspace_uuid: Optional[StrictStr] = None
    organization_uuid: Optional[StrictStr] = None
    window: MetricsWindowSchema
    totals: AIUsageTotals
    cost_source_breakdown: AIUsageCostSourceBreakdown
    by_provider: Dict[str, AIUsageSummary]
    by_model: Dict[str, AIUsageSummary]
    by_caller: Dict[str, AIUsageSummary]
    by_request_kind: Dict[str, AIUsageSummary]
    by_usage_class: Dict[str, AIUsageSummary]
    by_day: List[AIUsageDayBucket]
    __properties: ClassVar[List[str]] = ["workspace_uuid", "organization_uuid", "window", "totals", "cost_source_breakdown", "by_provider", "by_model", "by_caller", "by_request_kind", "by_usage_class", "by_day"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIMetricsSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of window
        if self.window:
            _dict['window'] = self.window.to_dict()
        # override the default output from pydantic by calling `to_dict()` of totals
        if self.totals:
            _dict['totals'] = self.totals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cost_source_breakdown
        if self.cost_source_breakdown:
            _dict['cost_source_breakdown'] = self.cost_source_breakdown.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in by_provider (dict)
        _field_dict = {}
        if self.by_provider:
            for _key_by_provider in self.by_provider:
                if self.by_provider[_key_by_provider]:
                    _field_dict[_key_by_provider] = self.by_provider[_key_by_provider].to_dict()
            _dict['by_provider'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in by_model (dict)
        _field_dict = {}
        if self.by_model:
            for _key_by_model in self.by_model:
                if self.by_model[_key_by_model]:
                    _field_dict[_key_by_model] = self.by_model[_key_by_model].to_dict()
            _dict['by_model'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in by_caller (dict)
        _field_dict = {}
        if self.by_caller:
            for _key_by_caller in self.by_caller:
                if self.by_caller[_key_by_caller]:
                    _field_dict[_key_by_caller] = self.by_caller[_key_by_caller].to_dict()
            _dict['by_caller'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in by_request_kind (dict)
        _field_dict = {}
        if self.by_request_kind:
            for _key_by_request_kind in self.by_request_kind:
                if self.by_request_kind[_key_by_request_kind]:
                    _field_dict[_key_by_request_kind] = self.by_request_kind[_key_by_request_kind].to_dict()
            _dict['by_request_kind'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in by_usage_class (dict)
        _field_dict = {}
        if self.by_usage_class:
            for _key_by_usage_class in self.by_usage_class:
                if self.by_usage_class[_key_by_usage_class]:
                    _field_dict[_key_by_usage_class] = self.by_usage_class[_key_by_usage_class].to_dict()
            _dict['by_usage_class'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in by_day (list)
        _items = []
        if self.by_day:
            for _item_by_day in self.by_day:
                if _item_by_day:
                    _items.append(_item_by_day.to_dict())
            _dict['by_day'] = _items
        # set to None if workspace_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.workspace_uuid is None and "workspace_uuid" in self.model_fields_set:
            _dict['workspace_uuid'] = None

        # set to None if organization_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.organization_uuid is None and "organization_uuid" in self.model_fields_set:
            _dict['organization_uuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIMetricsSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_uuid": obj.get("workspace_uuid"),
            "organization_uuid": obj.get("organization_uuid"),
            "window": MetricsWindowSchema.from_dict(obj["window"]) if obj.get("window") is not None else None,
            "totals": AIUsageTotals.from_dict(obj["totals"]) if obj.get("totals") is not None else None,
            "cost_source_breakdown": AIUsageCostSourceBreakdown.from_dict(obj["cost_source_breakdown"]) if obj.get("cost_source_breakdown") is not None else None,
            "by_provider": dict(
                (_k, AIUsageSummary.from_dict(_v))
                for _k, _v in obj["by_provider"].items()
            )
            if obj.get("by_provider") is not None
            else None,
            "by_model": dict(
                (_k, AIUsageSummary.from_dict(_v))
                for _k, _v in obj["by_model"].items()
            )
            if obj.get("by_model") is not None
            else None,
            "by_caller": dict(
                (_k, AIUsageSummary.from_dict(_v))
                for _k, _v in obj["by_caller"].items()
            )
            if obj.get("by_caller") is not None
            else None,
            "by_request_kind": dict(
                (_k, AIUsageSummary.from_dict(_v))
                for _k, _v in obj["by_request_kind"].items()
            )
            if obj.get("by_request_kind") is not None
            else None,
            "by_usage_class": dict(
                (_k, AIUsageSummary.from_dict(_v))
                for _k, _v in obj["by_usage_class"].items()
            )
            if obj.get("by_usage_class") is not None
            else None,
            "by_day": [AIUsageDayBucket.from_dict(_item) for _item in obj["by_day"]] if obj.get("by_day") is not None else None
        })
        return _obj


