# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyberwave.rest.models.workspace_ref_schema import WorkspaceRefSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APITokenSchema(BaseModel):
    """
    APITokenSchema
    """ # noqa: E501
    uuid: StrictStr
    token: StrictStr
    name: StrictStr
    workspace: StrictStr
    workspace_name: StrictStr
    workspaces: List[WorkspaceRefSchema]
    organization: Optional[StrictStr]
    token_type: StrictStr
    service_role: Optional[StrictStr]
    access_level: StrictStr
    metadata: Dict[str, Any]
    created_by: Optional[StrictStr]
    is_owned_by_caller: StrictBool
    expires_at: Optional[datetime]
    last_used_at: Optional[datetime]
    created_at: datetime
    updated_at: datetime
    revoked_at: Optional[datetime]
    __properties: ClassVar[List[str]] = ["uuid", "token", "name", "workspace", "workspace_name", "workspaces", "organization", "token_type", "service_role", "access_level", "metadata", "created_by", "is_owned_by_caller", "expires_at", "last_used_at", "created_at", "updated_at", "revoked_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APITokenSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in workspaces (list)
        _items = []
        if self.workspaces:
            for _item_workspaces in self.workspaces:
                if _item_workspaces:
                    _items.append(_item_workspaces.to_dict())
            _dict['workspaces'] = _items
        # set to None if organization (nullable) is None
        # and model_fields_set contains the field
        if self.organization is None and "organization" in self.model_fields_set:
            _dict['organization'] = None

        # set to None if service_role (nullable) is None
        # and model_fields_set contains the field
        if self.service_role is None and "service_role" in self.model_fields_set:
            _dict['service_role'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['created_by'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if last_used_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_used_at is None and "last_used_at" in self.model_fields_set:
            _dict['last_used_at'] = None

        # set to None if revoked_at (nullable) is None
        # and model_fields_set contains the field
        if self.revoked_at is None and "revoked_at" in self.model_fields_set:
            _dict['revoked_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APITokenSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "token": obj.get("token"),
            "name": obj.get("name"),
            "workspace": obj.get("workspace"),
            "workspace_name": obj.get("workspace_name"),
            "workspaces": [WorkspaceRefSchema.from_dict(_item) for _item in obj["workspaces"]] if obj.get("workspaces") is not None else None,
            "organization": obj.get("organization"),
            "token_type": obj.get("token_type"),
            "service_role": obj.get("service_role"),
            "access_level": obj.get("access_level"),
            "metadata": obj.get("metadata"),
            "created_by": obj.get("created_by"),
            "is_owned_by_caller": obj.get("is_owned_by_caller"),
            "expires_at": obj.get("expires_at"),
            "last_used_at": obj.get("last_used_at"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "revoked_at": obj.get("revoked_at")
        })
        return _obj


