# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AssetUpdateSchema(BaseModel):
    """
    AssetUpdateSchema
    """ # noqa: E501
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    visibility: Optional[StrictStr] = None
    workspace_uuid: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = None
    registry_id: Optional[StrictStr] = None
    registry_id_alias: Optional[StrictStr] = None
    fixed_base: Optional[StrictBool] = None
    universal_schema: Optional[Dict[str, Any]] = None
    supported_simulation_backends: Optional[List[StrictStr]] = None
    purchase_price: Optional[Union[StrictFloat, StrictInt]] = None
    monthly_price: Optional[Union[StrictFloat, StrictInt]] = None
    is_purchasable: Optional[StrictBool] = None
    is_rentable: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["name", "description", "visibility", "workspace_uuid", "metadata", "registry_id", "registry_id_alias", "fixed_base", "universal_schema", "supported_simulation_backends", "purchase_price", "monthly_price", "is_purchasable", "is_rentable"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssetUpdateSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if visibility (nullable) is None
        # and model_fields_set contains the field
        if self.visibility is None and "visibility" in self.model_fields_set:
            _dict['visibility'] = None

        # set to None if workspace_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.workspace_uuid is None and "workspace_uuid" in self.model_fields_set:
            _dict['workspace_uuid'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if registry_id (nullable) is None
        # and model_fields_set contains the field
        if self.registry_id is None and "registry_id" in self.model_fields_set:
            _dict['registry_id'] = None

        # set to None if registry_id_alias (nullable) is None
        # and model_fields_set contains the field
        if self.registry_id_alias is None and "registry_id_alias" in self.model_fields_set:
            _dict['registry_id_alias'] = None

        # set to None if fixed_base (nullable) is None
        # and model_fields_set contains the field
        if self.fixed_base is None and "fixed_base" in self.model_fields_set:
            _dict['fixed_base'] = None

        # set to None if universal_schema (nullable) is None
        # and model_fields_set contains the field
        if self.universal_schema is None and "universal_schema" in self.model_fields_set:
            _dict['universal_schema'] = None

        # set to None if supported_simulation_backends (nullable) is None
        # and model_fields_set contains the field
        if self.supported_simulation_backends is None and "supported_simulation_backends" in self.model_fields_set:
            _dict['supported_simulation_backends'] = None

        # set to None if purchase_price (nullable) is None
        # and model_fields_set contains the field
        if self.purchase_price is None and "purchase_price" in self.model_fields_set:
            _dict['purchase_price'] = None

        # set to None if monthly_price (nullable) is None
        # and model_fields_set contains the field
        if self.monthly_price is None and "monthly_price" in self.model_fields_set:
            _dict['monthly_price'] = None

        # set to None if is_purchasable (nullable) is None
        # and model_fields_set contains the field
        if self.is_purchasable is None and "is_purchasable" in self.model_fields_set:
            _dict['is_purchasable'] = None

        # set to None if is_rentable (nullable) is None
        # and model_fields_set contains the field
        if self.is_rentable is None and "is_rentable" in self.model_fields_set:
            _dict['is_rentable'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssetUpdateSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "visibility": obj.get("visibility"),
            "workspace_uuid": obj.get("workspace_uuid"),
            "metadata": obj.get("metadata"),
            "registry_id": obj.get("registry_id"),
            "registry_id_alias": obj.get("registry_id_alias"),
            "fixed_base": obj.get("fixed_base"),
            "universal_schema": obj.get("universal_schema"),
            "supported_simulation_backends": obj.get("supported_simulation_backends"),
            "purchase_price": obj.get("purchase_price"),
            "monthly_price": obj.get("monthly_price"),
            "is_purchasable": obj.get("is_purchasable"),
            "is_rentable": obj.get("is_rentable")
        })
        return _obj


