# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AssetGenerationCreateSchema(BaseModel):
    """
    AssetGenerationCreateSchema
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    prompt: Annotated[str, Field(min_length=3, strict=True, max_length=8000)]
    environment_uuid: StrictStr
    strategy: Optional[StrictStr] = 'auto'
    builder: StrictStr
    position: Optional[List[Union[StrictFloat, StrictInt]]] = None
    dimensions: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = None
    source_asset_uuid: Optional[StrictStr] = None
    target_twin_uuid: Optional[StrictStr] = None
    assistant_session_id: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    review_on_complete: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = ["name", "prompt", "environment_uuid", "strategy", "builder", "position", "dimensions", "source_asset_uuid", "target_twin_uuid", "assistant_session_id", "review_on_complete"]

    @field_validator('strategy')
    def strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['auto', 'programmatic']):
            raise ValueError("must be one of enum values ('auto', 'programmatic')")
        return value

    @field_validator('builder')
    def builder_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pencil', 'gearbox', 'forklift', 'hinged_enclosure', 'deployable_solar_array', 'wind_turbine', 'cement_cyclone', 'generic_enclosure']):
            raise ValueError("must be one of enum values ('pencil', 'gearbox', 'forklift', 'hinged_enclosure', 'deployable_solar_array', 'wind_turbine', 'cement_cyclone', 'generic_enclosure')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssetGenerationCreateSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if position (nullable) is None
        # and model_fields_set contains the field
        if self.position is None and "position" in self.model_fields_set:
            _dict['position'] = None

        # set to None if dimensions (nullable) is None
        # and model_fields_set contains the field
        if self.dimensions is None and "dimensions" in self.model_fields_set:
            _dict['dimensions'] = None

        # set to None if source_asset_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.source_asset_uuid is None and "source_asset_uuid" in self.model_fields_set:
            _dict['source_asset_uuid'] = None

        # set to None if target_twin_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.target_twin_uuid is None and "target_twin_uuid" in self.model_fields_set:
            _dict['target_twin_uuid'] = None

        # set to None if assistant_session_id (nullable) is None
        # and model_fields_set contains the field
        if self.assistant_session_id is None and "assistant_session_id" in self.model_fields_set:
            _dict['assistant_session_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssetGenerationCreateSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "prompt": obj.get("prompt"),
            "environment_uuid": obj.get("environment_uuid"),
            "strategy": obj.get("strategy") if obj.get("strategy") is not None else 'auto',
            "builder": obj.get("builder"),
            "position": obj.get("position"),
            "dimensions": obj.get("dimensions"),
            "source_asset_uuid": obj.get("source_asset_uuid"),
            "target_twin_uuid": obj.get("target_twin_uuid"),
            "assistant_session_id": obj.get("assistant_session_id"),
            "review_on_complete": obj.get("review_on_complete") if obj.get("review_on_complete") is not None else False
        })
        return _obj


