# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AssetGenerationSchema(BaseModel):
    """
    AssetGenerationSchema
    """ # noqa: E501
    uuid: StrictStr
    workspace_uuid: StrictStr
    environment_uuid: Optional[StrictStr] = None
    asset_uuid: Optional[StrictStr] = None
    source_asset_uuid: Optional[StrictStr] = None
    target_twin_uuid: Optional[StrictStr] = None
    acceptance_status: StrictStr
    asset_revision: Optional[StrictInt] = None
    twin_uuid: Optional[StrictStr] = None
    name: StrictStr
    prompt: StrictStr
    requested_strategy: StrictStr
    selected_strategy: Optional[StrictStr] = None
    status: StrictStr
    stage: StrictStr
    progress: StrictInt
    request_context: Dict[str, Any]
    result_manifest: Dict[str, Any]
    error: StrictStr
    created_at: datetime
    updated_at: datetime
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    preview_status: Optional[StrictStr] = None
    preview_image_url: Optional[StrictStr] = None
    preview_urdf_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["uuid", "workspace_uuid", "environment_uuid", "asset_uuid", "source_asset_uuid", "target_twin_uuid", "acceptance_status", "asset_revision", "twin_uuid", "name", "prompt", "requested_strategy", "selected_strategy", "status", "stage", "progress", "request_context", "result_manifest", "error", "created_at", "updated_at", "started_at", "completed_at", "preview_status", "preview_image_url", "preview_urdf_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssetGenerationSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if environment_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.environment_uuid is None and "environment_uuid" in self.model_fields_set:
            _dict['environment_uuid'] = None

        # set to None if asset_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.asset_uuid is None and "asset_uuid" in self.model_fields_set:
            _dict['asset_uuid'] = None

        # set to None if source_asset_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.source_asset_uuid is None and "source_asset_uuid" in self.model_fields_set:
            _dict['source_asset_uuid'] = None

        # set to None if target_twin_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.target_twin_uuid is None and "target_twin_uuid" in self.model_fields_set:
            _dict['target_twin_uuid'] = None

        # set to None if asset_revision (nullable) is None
        # and model_fields_set contains the field
        if self.asset_revision is None and "asset_revision" in self.model_fields_set:
            _dict['asset_revision'] = None

        # set to None if twin_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.twin_uuid is None and "twin_uuid" in self.model_fields_set:
            _dict['twin_uuid'] = None

        # set to None if selected_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.selected_strategy is None and "selected_strategy" in self.model_fields_set:
            _dict['selected_strategy'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if preview_status (nullable) is None
        # and model_fields_set contains the field
        if self.preview_status is None and "preview_status" in self.model_fields_set:
            _dict['preview_status'] = None

        # set to None if preview_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.preview_image_url is None and "preview_image_url" in self.model_fields_set:
            _dict['preview_image_url'] = None

        # set to None if preview_urdf_url (nullable) is None
        # and model_fields_set contains the field
        if self.preview_urdf_url is None and "preview_urdf_url" in self.model_fields_set:
            _dict['preview_urdf_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssetGenerationSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "workspace_uuid": obj.get("workspace_uuid"),
            "environment_uuid": obj.get("environment_uuid"),
            "asset_uuid": obj.get("asset_uuid"),
            "source_asset_uuid": obj.get("source_asset_uuid"),
            "target_twin_uuid": obj.get("target_twin_uuid"),
            "acceptance_status": obj.get("acceptance_status"),
            "asset_revision": obj.get("asset_revision"),
            "twin_uuid": obj.get("twin_uuid"),
            "name": obj.get("name"),
            "prompt": obj.get("prompt"),
            "requested_strategy": obj.get("requested_strategy"),
            "selected_strategy": obj.get("selected_strategy"),
            "status": obj.get("status"),
            "stage": obj.get("stage"),
            "progress": obj.get("progress"),
            "request_context": obj.get("request_context"),
            "result_manifest": obj.get("result_manifest"),
            "error": obj.get("error"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "started_at": obj.get("started_at"),
            "completed_at": obj.get("completed_at"),
            "preview_status": obj.get("preview_status"),
            "preview_image_url": obj.get("preview_image_url"),
            "preview_urdf_url": obj.get("preview_urdf_url")
        })
        return _obj


