# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyberwave.rest.models.compute_usage_day_bucket import ComputeUsageDayBucket
from cyberwave.rest.models.compute_usage_summary import ComputeUsageSummary
from cyberwave.rest.models.metrics_window_schema import MetricsWindowSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ComputeMetricsSchema(BaseModel):
    """
    Workspace-/org-scoped roll-up of billed compute workloads.  Mirrors the pricing rate-card COMPUTE split: ``by_class`` always carries a ``cloud`` and a ``simulation`` bucket (simulation = ``cyberwave-sim`` / ``mujoco-sim`` profiles). ``by_profile`` and ``by_command_type`` give the finer breakdown; ``by_day`` is a per-(day, class) series for charting.
    """ # noqa: E501
    workspace_uuid: Optional[StrictStr] = None
    organization_uuid: Optional[StrictStr] = None
    window: MetricsWindowSchema
    totals: ComputeUsageSummary
    by_class: Dict[str, ComputeUsageSummary]
    by_profile: Dict[str, ComputeUsageSummary]
    by_command_type: Dict[str, ComputeUsageSummary]
    by_day: List[ComputeUsageDayBucket]
    __properties: ClassVar[List[str]] = ["workspace_uuid", "organization_uuid", "window", "totals", "by_class", "by_profile", "by_command_type", "by_day"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComputeMetricsSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of window
        if self.window:
            _dict['window'] = self.window.to_dict()
        # override the default output from pydantic by calling `to_dict()` of totals
        if self.totals:
            _dict['totals'] = self.totals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in by_class (dict)
        _field_dict = {}
        if self.by_class:
            for _key_by_class in self.by_class:
                if self.by_class[_key_by_class]:
                    _field_dict[_key_by_class] = self.by_class[_key_by_class].to_dict()
            _dict['by_class'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in by_profile (dict)
        _field_dict = {}
        if self.by_profile:
            for _key_by_profile in self.by_profile:
                if self.by_profile[_key_by_profile]:
                    _field_dict[_key_by_profile] = self.by_profile[_key_by_profile].to_dict()
            _dict['by_profile'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in by_command_type (dict)
        _field_dict = {}
        if self.by_command_type:
            for _key_by_command_type in self.by_command_type:
                if self.by_command_type[_key_by_command_type]:
                    _field_dict[_key_by_command_type] = self.by_command_type[_key_by_command_type].to_dict()
            _dict['by_command_type'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in by_day (list)
        _items = []
        if self.by_day:
            for _item_by_day in self.by_day:
                if _item_by_day:
                    _items.append(_item_by_day.to_dict())
            _dict['by_day'] = _items
        # set to None if workspace_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.workspace_uuid is None and "workspace_uuid" in self.model_fields_set:
            _dict['workspace_uuid'] = None

        # set to None if organization_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.organization_uuid is None and "organization_uuid" in self.model_fields_set:
            _dict['organization_uuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComputeMetricsSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_uuid": obj.get("workspace_uuid"),
            "organization_uuid": obj.get("organization_uuid"),
            "window": MetricsWindowSchema.from_dict(obj["window"]) if obj.get("window") is not None else None,
            "totals": ComputeUsageSummary.from_dict(obj["totals"]) if obj.get("totals") is not None else None,
            "by_class": dict(
                (_k, ComputeUsageSummary.from_dict(_v))
                for _k, _v in obj["by_class"].items()
            )
            if obj.get("by_class") is not None
            else None,
            "by_profile": dict(
                (_k, ComputeUsageSummary.from_dict(_v))
                for _k, _v in obj["by_profile"].items()
            )
            if obj.get("by_profile") is not None
            else None,
            "by_command_type": dict(
                (_k, ComputeUsageSummary.from_dict(_v))
                for _k, _v in obj["by_command_type"].items()
            )
            if obj.get("by_command_type") is not None
            else None,
            "by_day": [ComputeUsageDayBucket.from_dict(_item) for _item in obj["by_day"]] if obj.get("by_day") is not None else None
        })
        return _obj


