# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from cyberwave.rest.models.control_action_input_trigger_schema import ControlActionInputTriggerSchema
from cyberwave.rest.models.control_operator_ui_schema import ControlOperatorUISchema
from cyberwave.rest.models.input_mappings_value2 import InputMappingsValue2
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ControlActionDraftConfigV6Schema(BaseModel):
    """
    ControlActionDraftConfigV6Schema
    """ # noqa: E501
    version: Optional[StrictInt] = 6
    capability_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    name: Annotated[str, Field(min_length=1, strict=True, max_length=150)]
    input_policy_uuids: Optional[Annotated[List[UUID], Field(max_length=16)]] = None
    policy_uuid: Optional[UUID] = None
    operator_ui: Optional[ControlOperatorUISchema] = None
    input_trigger: Optional[ControlActionInputTriggerSchema] = None
    input_mappings: Optional[Dict[str, InputMappingsValue2]] = None
    workflow_node_uuid: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["version", "capability_id", "name", "input_policy_uuids", "policy_uuid", "operator_ui", "input_trigger", "input_mappings", "workflow_node_uuid"]

    @field_validator('version')
    def version_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([6]):
            raise ValueError("must be one of enum values (6)")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ControlActionDraftConfigV6Schema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of operator_ui
        if self.operator_ui:
            _dict['operator_ui'] = self.operator_ui.to_dict()
        # override the default output from pydantic by calling `to_dict()` of input_trigger
        if self.input_trigger:
            _dict['input_trigger'] = self.input_trigger.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in input_mappings (dict)
        _field_dict = {}
        if self.input_mappings:
            for _key_input_mappings in self.input_mappings:
                if self.input_mappings[_key_input_mappings]:
                    _field_dict[_key_input_mappings] = self.input_mappings[_key_input_mappings].to_dict()
            _dict['input_mappings'] = _field_dict
        # set to None if policy_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.policy_uuid is None and "policy_uuid" in self.model_fields_set:
            _dict['policy_uuid'] = None

        # set to None if operator_ui (nullable) is None
        # and model_fields_set contains the field
        if self.operator_ui is None and "operator_ui" in self.model_fields_set:
            _dict['operator_ui'] = None

        # set to None if input_trigger (nullable) is None
        # and model_fields_set contains the field
        if self.input_trigger is None and "input_trigger" in self.model_fields_set:
            _dict['input_trigger'] = None

        # set to None if workflow_node_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.workflow_node_uuid is None and "workflow_node_uuid" in self.model_fields_set:
            _dict['workflow_node_uuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ControlActionDraftConfigV6Schema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version") if obj.get("version") is not None else 6,
            "capability_id": obj.get("capability_id"),
            "name": obj.get("name"),
            "input_policy_uuids": obj.get("input_policy_uuids"),
            "policy_uuid": obj.get("policy_uuid"),
            "operator_ui": ControlOperatorUISchema.from_dict(obj["operator_ui"]) if obj.get("operator_ui") is not None else None,
            "input_trigger": ControlActionInputTriggerSchema.from_dict(obj["input_trigger"]) if obj.get("input_trigger") is not None else None,
            "input_mappings": dict(
                (_k, InputMappingsValue2.from_dict(_v))
                for _k, _v in obj["input_mappings"].items()
            )
            if obj.get("input_mappings") is not None
            else None,
            "workflow_node_uuid": obj.get("workflow_node_uuid")
        })
        return _obj


