# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreditLedgerEntrySchema(BaseModel):
    """
    CreditLedgerEntrySchema
    """ # noqa: E501
    transaction_uuid: StrictStr
    kind: StrictStr
    direction: StrictStr
    amount_credits: Annotated[str, Field(strict=True)]
    category: Optional[StrictStr] = None
    billable: Optional[StrictBool] = True
    usage_class: Optional[StrictStr] = None
    created_at: StrictStr
    source: Optional[StrictStr] = None
    has_invoice: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = ["transaction_uuid", "kind", "direction", "amount_credits", "category", "billable", "usage_class", "created_at", "source", "has_invoice"]

    @field_validator('amount_credits')
    def amount_credits_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$", value):
            raise ValueError(r"must validate the regular expression /^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreditLedgerEntrySchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if category (nullable) is None
        # and model_fields_set contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict['category'] = None

        # set to None if usage_class (nullable) is None
        # and model_fields_set contains the field
        if self.usage_class is None and "usage_class" in self.model_fields_set:
            _dict['usage_class'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreditLedgerEntrySchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transaction_uuid": obj.get("transaction_uuid"),
            "kind": obj.get("kind"),
            "direction": obj.get("direction"),
            "amount_credits": obj.get("amount_credits"),
            "category": obj.get("category"),
            "billable": obj.get("billable") if obj.get("billable") is not None else True,
            "usage_class": obj.get("usage_class"),
            "created_at": obj.get("created_at"),
            "source": obj.get("source"),
            "has_invoice": obj.get("has_invoice") if obj.get("has_invoice") is not None else False
        })
        return _obj


