# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JointCalibrationSchema(BaseModel):
    """
    Schema for a single joint's calibration (request/response).
    """ # noqa: E501
    range_min: Union[StrictFloat, StrictInt]
    range_max: Union[StrictFloat, StrictInt]
    homing_offset: Union[StrictFloat, StrictInt]
    drive_mode: StrictStr
    id: StrictStr
    lower: Optional[Union[StrictFloat, StrictInt]] = None
    upper: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["range_min", "range_max", "homing_offset", "drive_mode", "id", "lower", "upper"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JointCalibrationSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if lower (nullable) is None
        # and model_fields_set contains the field
        if self.lower is None and "lower" in self.model_fields_set:
            _dict['lower'] = None

        # set to None if upper (nullable) is None
        # and model_fields_set contains the field
        if self.upper is None and "upper" in self.model_fields_set:
            _dict['upper'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JointCalibrationSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "range_min": obj.get("range_min"),
            "range_max": obj.get("range_max"),
            "homing_offset": obj.get("homing_offset"),
            "drive_mode": obj.get("drive_mode"),
            "id": obj.get("id"),
            "lower": obj.get("lower"),
            "upper": obj.get("upper")
        })
        return _obj


