# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from cyberwave.rest.models.joint_schema_limits_value import JointSchemaLimitsValue
from cyberwave.rest.models.mimic_joint_schema import MimicJointSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JointSchema(BaseModel):
    """
    JointSchema
    """ # noqa: E501
    name: StrictStr
    type: StrictStr
    parent_link: StrictStr
    child_link: StrictStr
    axis: Optional[List[Union[StrictFloat, StrictInt]]]
    limits: Optional[Dict[str, Optional[JointSchemaLimitsValue]]]
    origin: Optional[Dict[str, List[Union[StrictFloat, StrictInt]]]]
    mimic: Optional[MimicJointSchema] = None
    home_position: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["name", "type", "parent_link", "child_link", "axis", "limits", "origin", "mimic", "home_position"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JointSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in limits (dict)
        _field_dict = {}
        if self.limits:
            for _key_limits in self.limits:
                if self.limits[_key_limits]:
                    _field_dict[_key_limits] = self.limits[_key_limits].to_dict()
            _dict['limits'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of mimic
        if self.mimic:
            _dict['mimic'] = self.mimic.to_dict()
        # set to None if axis (nullable) is None
        # and model_fields_set contains the field
        if self.axis is None and "axis" in self.model_fields_set:
            _dict['axis'] = None

        # set to None if limits (nullable) is None
        # and model_fields_set contains the field
        if self.limits is None and "limits" in self.model_fields_set:
            _dict['limits'] = None

        # set to None if origin (nullable) is None
        # and model_fields_set contains the field
        if self.origin is None and "origin" in self.model_fields_set:
            _dict['origin'] = None

        # set to None if mimic (nullable) is None
        # and model_fields_set contains the field
        if self.mimic is None and "mimic" in self.model_fields_set:
            _dict['mimic'] = None

        # set to None if home_position (nullable) is None
        # and model_fields_set contains the field
        if self.home_position is None and "home_position" in self.model_fields_set:
            _dict['home_position'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JointSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "parent_link": obj.get("parent_link"),
            "child_link": obj.get("child_link"),
            "axis": obj.get("axis"),
            "limits": dict(
                (_k, JointSchemaLimitsValue.from_dict(_v))
                for _k, _v in obj["limits"].items()
            )
            if obj.get("limits") is not None
            else None,
            "origin": obj.get("origin"),
            "mimic": MimicJointSchema.from_dict(obj["mimic"]) if obj.get("mimic") is not None else None,
            "home_position": obj.get("home_position")
        })
        return _obj


