# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class LabAccessResponseSchema(BaseModel):
    """
    LabAccessResponseSchema
    """ # noqa: E501
    success: StrictBool
    session_status: StrictStr
    environment_uuid: StrictStr
    environment_name: StrictStr
    role: StrictStr
    message: StrictStr
    already_had_session: Optional[StrictBool] = False
    queue_position: Optional[StrictInt] = None
    estimated_wait_minutes: Optional[StrictInt] = None
    session_expires_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["success", "session_status", "environment_uuid", "environment_name", "role", "message", "already_had_session", "queue_position", "estimated_wait_minutes", "session_expires_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LabAccessResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if queue_position (nullable) is None
        # and model_fields_set contains the field
        if self.queue_position is None and "queue_position" in self.model_fields_set:
            _dict['queue_position'] = None

        # set to None if estimated_wait_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_wait_minutes is None and "estimated_wait_minutes" in self.model_fields_set:
            _dict['estimated_wait_minutes'] = None

        # set to None if session_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.session_expires_at is None and "session_expires_at" in self.model_fields_set:
            _dict['session_expires_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LabAccessResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "session_status": obj.get("session_status"),
            "environment_uuid": obj.get("environment_uuid"),
            "environment_name": obj.get("environment_name"),
            "role": obj.get("role"),
            "message": obj.get("message"),
            "already_had_session": obj.get("already_had_session") if obj.get("already_had_session") is not None else False,
            "queue_position": obj.get("queue_position"),
            "estimated_wait_minutes": obj.get("estimated_wait_minutes"),
            "session_expires_at": obj.get("session_expires_at")
        })
        return _obj


