# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LabKind(str, Enum):
    """
    The class of hardware a lab environment exposes.  Each kind is its own pool with its own FIFO queue: a user who asked for an arm must never be handed a rover, and ``LabQueueService._promote_next`` must not promote a queued arm user onto a freed UGV.
    """

    """
    allowed enum values
    """
    MANIPULATOR = 'manipulator'
    UGV = 'ugv'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LabKind from a JSON string"""
        return cls(json.loads(json_str))


