# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from cyberwave.rest.models.ml_training_metrics_log_schema import MLTrainingMetricsLogSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MLTrainingMetricsUpdateSchema(BaseModel):
    """
    Schema for updating training metrics logs.  Used when updating training metrics via PUT /mltrainings/{uuid}/metrics This allows logging multiple steps at once or single step updates.  Payload options: - Single step: {\"step\": 100, \"log\": {\"loss\": 0.5}, \"eta\": \"...\", \"loss\": 0.5} - Multiple steps: {\"logs\": [{\"step\": 100, \"log\": {...}, ...}, ...]}
    """ # noqa: E501
    step: Optional[StrictInt] = None
    log: Optional[Dict[str, Any]] = None
    eta: Optional[datetime] = None
    loss: Optional[Union[StrictFloat, StrictInt]] = None
    logs: Optional[List[MLTrainingMetricsLogSchema]] = None
    __properties: ClassVar[List[str]] = ["step", "log", "eta", "loss", "logs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MLTrainingMetricsUpdateSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in logs (list)
        _items = []
        if self.logs:
            for _item_logs in self.logs:
                if _item_logs:
                    _items.append(_item_logs.to_dict())
            _dict['logs'] = _items
        # set to None if step (nullable) is None
        # and model_fields_set contains the field
        if self.step is None and "step" in self.model_fields_set:
            _dict['step'] = None

        # set to None if log (nullable) is None
        # and model_fields_set contains the field
        if self.log is None and "log" in self.model_fields_set:
            _dict['log'] = None

        # set to None if eta (nullable) is None
        # and model_fields_set contains the field
        if self.eta is None and "eta" in self.model_fields_set:
            _dict['eta'] = None

        # set to None if loss (nullable) is None
        # and model_fields_set contains the field
        if self.loss is None and "loss" in self.model_fields_set:
            _dict['loss'] = None

        # set to None if logs (nullable) is None
        # and model_fields_set contains the field
        if self.logs is None and "logs" in self.model_fields_set:
            _dict['logs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MLTrainingMetricsUpdateSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "step": obj.get("step"),
            "log": obj.get("log"),
            "eta": obj.get("eta"),
            "loss": obj.get("loss"),
            "logs": [MLTrainingMetricsLogSchema.from_dict(_item) for _item in obj["logs"]] if obj.get("logs") is not None else None
        })
        return _obj


