# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cyberwave.rest.models.rates_value_value import RatesValueValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrganizationCreditAccountSchema(BaseModel):
    """
    OrganizationCreditAccountSchema
    """ # noqa: E501
    organization_uuid: StrictStr
    balance_credits: Annotated[str, Field(strict=True)]
    status: StrictStr
    warning_threshold_credits: Annotated[str, Field(strict=True)]
    enforcement_enabled: StrictBool
    rates: Dict[str, Dict[str, RatesValueValue]]
    manual_block: Optional[StrictBool] = False
    manual_block_reason: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["organization_uuid", "balance_credits", "status", "warning_threshold_credits", "enforcement_enabled", "rates", "manual_block", "manual_block_reason"]

    @field_validator('balance_credits')
    def balance_credits_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$", value):
            raise ValueError(r"must validate the regular expression /^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/")
        return value

    @field_validator('warning_threshold_credits')
    def warning_threshold_credits_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$", value):
            raise ValueError(r"must validate the regular expression /^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrganizationCreditAccountSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in rates (dict of dict)
        _field_dict_of_dict = {}
        if self.rates:
            for _key_rates, _value_rates in self.rates.items():
                if _value_rates is not None:
                    _field_dict_of_dict[_key_rates] = {
                        _key: _value.to_dict() for _key, _value in _value_rates.items()
                    }
            _dict['rates'] = _field_dict_of_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrganizationCreditAccountSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organization_uuid": obj.get("organization_uuid"),
            "balance_credits": obj.get("balance_credits"),
            "status": obj.get("status"),
            "warning_threshold_credits": obj.get("warning_threshold_credits"),
            "enforcement_enabled": obj.get("enforcement_enabled"),
            "rates": dict(
                (_k, dict(
                    (_ik, RatesValueValue.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj["rates"].items()
            )
            if obj.get("rates") is not None
            else None,
            "manual_block": obj.get("manual_block") if obj.get("manual_block") is not None else False,
            "manual_block_reason": obj.get("manual_block_reason") if obj.get("manual_block_reason") is not None else ''
        })
        return _obj


