# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PartnerIntegrationSchema(BaseModel):
    """
    PartnerIntegrationSchema
    """ # noqa: E501
    uuid: StrictStr
    organization_uuid: StrictStr
    created_by_uuid: Optional[StrictStr] = None
    partner_key: StrictStr
    integration_name: StrictStr
    authentication_type: StrictStr
    credential_type: StrictStr
    secret_type: StrictStr
    grant_type: StrictStr
    token_format: StrictStr
    authorization_endpoint: StrictStr
    token_endpoint: StrictStr
    domain: StrictStr
    integration_client_id: StrictStr
    username: StrictStr
    status: StrictStr
    status_detail: StrictStr
    external_connector_id: StrictStr
    is_service_active: StrictBool
    expiration_date: Optional[datetime] = None
    last_token_fetched_at: Optional[datetime] = None
    last_verified_at: Optional[datetime] = None
    last_registered_at: Optional[datetime] = None
    metadata: Dict[str, Any]
    has_password: StrictBool
    has_oauth_client_secret: StrictBool
    has_client_secret: StrictBool
    has_inbound_secret: StrictBool
    connector_base_url: Optional[StrictStr] = None
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["uuid", "organization_uuid", "created_by_uuid", "partner_key", "integration_name", "authentication_type", "credential_type", "secret_type", "grant_type", "token_format", "authorization_endpoint", "token_endpoint", "domain", "integration_client_id", "username", "status", "status_detail", "external_connector_id", "is_service_active", "expiration_date", "last_token_fetched_at", "last_verified_at", "last_registered_at", "metadata", "has_password", "has_oauth_client_secret", "has_client_secret", "has_inbound_secret", "connector_base_url", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PartnerIntegrationSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if created_by_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_uuid is None and "created_by_uuid" in self.model_fields_set:
            _dict['created_by_uuid'] = None

        # set to None if expiration_date (nullable) is None
        # and model_fields_set contains the field
        if self.expiration_date is None and "expiration_date" in self.model_fields_set:
            _dict['expiration_date'] = None

        # set to None if last_token_fetched_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_token_fetched_at is None and "last_token_fetched_at" in self.model_fields_set:
            _dict['last_token_fetched_at'] = None

        # set to None if last_verified_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_verified_at is None and "last_verified_at" in self.model_fields_set:
            _dict['last_verified_at'] = None

        # set to None if last_registered_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_registered_at is None and "last_registered_at" in self.model_fields_set:
            _dict['last_registered_at'] = None

        # set to None if connector_base_url (nullable) is None
        # and model_fields_set contains the field
        if self.connector_base_url is None and "connector_base_url" in self.model_fields_set:
            _dict['connector_base_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PartnerIntegrationSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "organization_uuid": obj.get("organization_uuid"),
            "created_by_uuid": obj.get("created_by_uuid"),
            "partner_key": obj.get("partner_key"),
            "integration_name": obj.get("integration_name"),
            "authentication_type": obj.get("authentication_type"),
            "credential_type": obj.get("credential_type"),
            "secret_type": obj.get("secret_type"),
            "grant_type": obj.get("grant_type"),
            "token_format": obj.get("token_format"),
            "authorization_endpoint": obj.get("authorization_endpoint"),
            "token_endpoint": obj.get("token_endpoint"),
            "domain": obj.get("domain"),
            "integration_client_id": obj.get("integration_client_id"),
            "username": obj.get("username"),
            "status": obj.get("status"),
            "status_detail": obj.get("status_detail"),
            "external_connector_id": obj.get("external_connector_id"),
            "is_service_active": obj.get("is_service_active"),
            "expiration_date": obj.get("expiration_date"),
            "last_token_fetched_at": obj.get("last_token_fetched_at"),
            "last_verified_at": obj.get("last_verified_at"),
            "last_registered_at": obj.get("last_registered_at"),
            "metadata": obj.get("metadata"),
            "has_password": obj.get("has_password"),
            "has_oauth_client_secret": obj.get("has_oauth_client_secret"),
            "has_client_secret": obj.get("has_client_secret"),
            "has_inbound_secret": obj.get("has_inbound_secret"),
            "connector_base_url": obj.get("connector_base_url"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


