# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cyberwave.rest.models.items_inner import ItemsInner
from cyberwave.rest.models.pinned_workspace_view_schema import PinnedWorkspaceViewSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PinnedWorkspaceLayoutSchema(BaseModel):
    """
    PinnedWorkspaceLayoutSchema
    """ # noqa: E501
    version: StrictInt
    route_pins_version: Optional[StrictInt] = None
    map_pins_version: Optional[StrictInt] = None
    twin_items: Optional[Dict[str, List[PinnedWorkspaceViewSchema]]] = Field(default=None, alias="twinItems")
    remove: Optional[StrictBool] = False
    name: Annotated[str, Field(min_length=1, strict=True, max_length=80)]
    items: Annotated[List[ItemsInner], Field(max_length=100)]
    __properties: ClassVar[List[str]] = ["version", "route_pins_version", "map_pins_version", "twinItems", "remove", "name", "items"]

    @field_validator('version')
    def version_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set([1]):
            raise ValueError("must be one of enum values (1)")
        return value

    @field_validator('route_pins_version')
    def route_pins_version_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1]):
            raise ValueError("must be one of enum values (1)")
        return value

    @field_validator('map_pins_version')
    def map_pins_version_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1]):
            raise ValueError("must be one of enum values (1)")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PinnedWorkspaceLayoutSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in twin_items (dict of array)
        _field_dict_of_array = {}
        if self.twin_items:
            for _key_twin_items in self.twin_items:
                if self.twin_items[_key_twin_items] is not None:
                    _field_dict_of_array[_key_twin_items] = [
                        _item.to_dict() for _item in self.twin_items[_key_twin_items]
                    ]
            _dict['twinItems'] = _field_dict_of_array
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # set to None if route_pins_version (nullable) is None
        # and model_fields_set contains the field
        if self.route_pins_version is None and "route_pins_version" in self.model_fields_set:
            _dict['route_pins_version'] = None

        # set to None if map_pins_version (nullable) is None
        # and model_fields_set contains the field
        if self.map_pins_version is None and "map_pins_version" in self.model_fields_set:
            _dict['map_pins_version'] = None

        # set to None if twin_items (nullable) is None
        # and model_fields_set contains the field
        if self.twin_items is None and "twin_items" in self.model_fields_set:
            _dict['twinItems'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PinnedWorkspaceLayoutSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "route_pins_version": obj.get("route_pins_version"),
            "map_pins_version": obj.get("map_pins_version"),
            "twinItems": dict(
                (_k,
                        [PinnedWorkspaceViewSchema.from_dict(_item) for _item in _v]
                        if _v is not None
                        else None
                )
                for _k, _v in obj.get("twinItems", {}).items()
            ),
            "remove": obj.get("remove") if obj.get("remove") is not None else False,
            "name": obj.get("name"),
            "items": [ItemsInner.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None
        })
        return _obj


