# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cyberwave.rest.models.replay_timeline_event_schema import ReplayTimelineEventSchema
from cyberwave.rest.models.replay_timeline_window_schema import ReplayTimelineWindowSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ReplayTimelineWindowEventsResponseSchema(BaseModel):
    """
    A keyset page of window annotations, resolved without any recording.  ``windows`` echoes the merged ranges actually queried, and ``windows_coalesced`` reports that too many ranges were requested and they were collapsed to their overall span.
    """ # noqa: E501
    association_policy: Optional[StrictStr] = 'window_annotation'
    windows: List[ReplayTimelineWindowSchema]
    windows_coalesced: Optional[StrictBool] = False
    selected_twin_uuid: Optional[StrictStr] = None
    page_size: StrictInt
    has_more: StrictBool
    next_cursor: Optional[StrictStr] = None
    events: List[ReplayTimelineEventSchema]
    __properties: ClassVar[List[str]] = ["association_policy", "windows", "windows_coalesced", "selected_twin_uuid", "page_size", "has_more", "next_cursor", "events"]

    @field_validator('association_policy')
    def association_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['window_annotation']):
            raise ValueError("must be one of enum values ('window_annotation')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplayTimelineWindowEventsResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in windows (list)
        _items = []
        if self.windows:
            for _item_windows in self.windows:
                if _item_windows:
                    _items.append(_item_windows.to_dict())
            _dict['windows'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                if _item_events:
                    _items.append(_item_events.to_dict())
            _dict['events'] = _items
        # set to None if selected_twin_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.selected_twin_uuid is None and "selected_twin_uuid" in self.model_fields_set:
            _dict['selected_twin_uuid'] = None

        # set to None if next_cursor (nullable) is None
        # and model_fields_set contains the field
        if self.next_cursor is None and "next_cursor" in self.model_fields_set:
            _dict['next_cursor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplayTimelineWindowEventsResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "association_policy": obj.get("association_policy") if obj.get("association_policy") is not None else 'window_annotation',
            "windows": [ReplayTimelineWindowSchema.from_dict(_item) for _item in obj["windows"]] if obj.get("windows") is not None else None,
            "windows_coalesced": obj.get("windows_coalesced") if obj.get("windows_coalesced") is not None else False,
            "selected_twin_uuid": obj.get("selected_twin_uuid"),
            "page_size": obj.get("page_size"),
            "has_more": obj.get("has_more"),
            "next_cursor": obj.get("next_cursor"),
            "events": [ReplayTimelineEventSchema.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None
        })
        return _obj


