# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RLTaskSceneEntityJointHintSchema(BaseModel):
    """
    One controllable joint projected for the composer UI (mirrors ``DerivedJointHint``).
    """ # noqa: E501
    name: StrictStr
    type: StrictStr
    parent_link: Optional[StrictStr] = ''
    child_link: Optional[StrictStr] = ''
    has_limits: Optional[StrictBool] = False
    lower: Optional[Union[StrictFloat, StrictInt]] = None
    upper: Optional[Union[StrictFloat, StrictInt]] = None
    home_position: Optional[Union[StrictFloat, StrictInt]] = None
    current_position: Optional[Union[StrictFloat, StrictInt]] = None
    initial_position: Optional[Union[StrictFloat, StrictInt]] = 0.0
    initial_position_source: Optional[StrictStr] = 'default'
    velocity_limit: Optional[Union[StrictFloat, StrictInt]] = None
    effort_limit: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["name", "type", "parent_link", "child_link", "has_limits", "lower", "upper", "home_position", "current_position", "initial_position", "initial_position_source", "velocity_limit", "effort_limit"]

    @field_validator('initial_position_source')
    def initial_position_source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['twin_joint_state', 'schema_home', 'default']):
            raise ValueError("must be one of enum values ('twin_joint_state', 'schema_home', 'default')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RLTaskSceneEntityJointHintSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if lower (nullable) is None
        # and model_fields_set contains the field
        if self.lower is None and "lower" in self.model_fields_set:
            _dict['lower'] = None

        # set to None if upper (nullable) is None
        # and model_fields_set contains the field
        if self.upper is None and "upper" in self.model_fields_set:
            _dict['upper'] = None

        # set to None if home_position (nullable) is None
        # and model_fields_set contains the field
        if self.home_position is None and "home_position" in self.model_fields_set:
            _dict['home_position'] = None

        # set to None if current_position (nullable) is None
        # and model_fields_set contains the field
        if self.current_position is None and "current_position" in self.model_fields_set:
            _dict['current_position'] = None

        # set to None if velocity_limit (nullable) is None
        # and model_fields_set contains the field
        if self.velocity_limit is None and "velocity_limit" in self.model_fields_set:
            _dict['velocity_limit'] = None

        # set to None if effort_limit (nullable) is None
        # and model_fields_set contains the field
        if self.effort_limit is None and "effort_limit" in self.model_fields_set:
            _dict['effort_limit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RLTaskSceneEntityJointHintSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "parent_link": obj.get("parent_link") if obj.get("parent_link") is not None else '',
            "child_link": obj.get("child_link") if obj.get("child_link") is not None else '',
            "has_limits": obj.get("has_limits") if obj.get("has_limits") is not None else False,
            "lower": obj.get("lower"),
            "upper": obj.get("upper"),
            "home_position": obj.get("home_position"),
            "current_position": obj.get("current_position"),
            "initial_position": obj.get("initial_position") if obj.get("initial_position") is not None else 0.0,
            "initial_position_source": obj.get("initial_position_source") if obj.get("initial_position_source") is not None else 'default',
            "velocity_limit": obj.get("velocity_limit"),
            "effort_limit": obj.get("effort_limit")
        })
        return _obj


