# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RLTaskRegenerateSceneSchema(BaseModel):
    """
    Optional inputs for regenerating the SceneCfg source file.
    """ # noqa: E501
    scene_cfg_path: Optional[StrictStr] = None
    factory_name: Optional[StrictStr] = None
    num_envs_default: Optional[StrictInt] = None
    env_spacing_default: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["scene_cfg_path", "factory_name", "num_envs_default", "env_spacing_default"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RLTaskRegenerateSceneSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if scene_cfg_path (nullable) is None
        # and model_fields_set contains the field
        if self.scene_cfg_path is None and "scene_cfg_path" in self.model_fields_set:
            _dict['scene_cfg_path'] = None

        # set to None if factory_name (nullable) is None
        # and model_fields_set contains the field
        if self.factory_name is None and "factory_name" in self.model_fields_set:
            _dict['factory_name'] = None

        # set to None if num_envs_default (nullable) is None
        # and model_fields_set contains the field
        if self.num_envs_default is None and "num_envs_default" in self.model_fields_set:
            _dict['num_envs_default'] = None

        # set to None if env_spacing_default (nullable) is None
        # and model_fields_set contains the field
        if self.env_spacing_default is None and "env_spacing_default" in self.model_fields_set:
            _dict['env_spacing_default'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RLTaskRegenerateSceneSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scene_cfg_path": obj.get("scene_cfg_path"),
            "factory_name": obj.get("factory_name"),
            "num_envs_default": obj.get("num_envs_default"),
            "env_spacing_default": obj.get("env_spacing_default")
        })
        return _obj


