# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TemplateTwinSummarySchema(BaseModel):
    """
    TemplateTwinSummarySchema
    """ # noqa: E501
    name: StrictStr
    asset_name: StrictStr
    asset_uuid: Optional[StrictStr] = None
    monthly_price: Optional[Union[StrictFloat, StrictInt]] = None
    purchase_price: Optional[Union[StrictFloat, StrictInt]] = None
    is_purchasable: Optional[StrictBool] = True
    is_rentable: Optional[StrictBool] = True
    __properties: ClassVar[List[str]] = ["name", "asset_name", "asset_uuid", "monthly_price", "purchase_price", "is_purchasable", "is_rentable"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplateTwinSummarySchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if asset_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.asset_uuid is None and "asset_uuid" in self.model_fields_set:
            _dict['asset_uuid'] = None

        # set to None if monthly_price (nullable) is None
        # and model_fields_set contains the field
        if self.monthly_price is None and "monthly_price" in self.model_fields_set:
            _dict['monthly_price'] = None

        # set to None if purchase_price (nullable) is None
        # and model_fields_set contains the field
        if self.purchase_price is None and "purchase_price" in self.model_fields_set:
            _dict['purchase_price'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplateTwinSummarySchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "asset_name": obj.get("asset_name"),
            "asset_uuid": obj.get("asset_uuid"),
            "monthly_price": obj.get("monthly_price"),
            "purchase_price": obj.get("purchase_price"),
            "is_purchasable": obj.get("is_purchasable") if obj.get("is_purchasable") is not None else True,
            "is_rentable": obj.get("is_rentable") if obj.get("is_rentable") is not None else True
        })
        return _obj


