# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyberwave.rest.models.joint_calibration import JointCalibration
from typing import Optional, Set
from typing_extensions import Self

class TwinJointCalibrationSchema(BaseModel):
    """
    TwinJointCalibrationSchema
    """ # noqa: E501
    joint_calibration: Dict[str, JointCalibration]
    robot_type: Optional[StrictStr] = 'follower'
    __properties: ClassVar[List[str]] = ["joint_calibration", "robot_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TwinJointCalibrationSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in joint_calibration (dict)
        _field_dict = {}
        if self.joint_calibration:
            for _key_joint_calibration in self.joint_calibration:
                if self.joint_calibration[_key_joint_calibration]:
                    _field_dict[_key_joint_calibration] = self.joint_calibration[_key_joint_calibration].to_dict()
            _dict['joint_calibration'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TwinJointCalibrationSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "joint_calibration": dict(
                (_k, JointCalibration.from_dict(_v))
                for _k, _v in obj["joint_calibration"].items()
            )
            if obj.get("joint_calibration") is not None
            else None,
            "robot_type": obj.get("robot_type") if obj.get("robot_type") is not None else 'follower'
        })
        return _obj


