# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkflowWorkerSourceSchema(BaseModel):
    """
    Response for ``GET /workflows/{uuid}/worker-source``.  ``materialized_source`` is what actually ships to the edge — the override when one is saved, otherwise the autogenerated source. ``autogenerated_source`` is always the current compiler output (or ``None`` when the graph doesn't compile) so the UI can diff against an override and offer \"restore\". ``is_stale`` is ``true`` when an override is saved but the graph has changed since (warn-only). ``autogen_error`` carries a human-readable reason when autogeneration failed, so an override-only workflow can still explain why there's no baseline.
    """ # noqa: E501
    workflow_uuid: StrictStr
    filename: Optional[StrictStr] = None
    materialized_source: Optional[StrictStr] = None
    autogenerated_source: Optional[StrictStr] = None
    is_overridden: Optional[StrictBool] = False
    is_stale: Optional[StrictBool] = False
    compiled_kind: Optional[StrictStr] = None
    autogen_error: Optional[StrictStr] = None
    warnings: Optional[List[StrictStr]] = None
    updated_at: Optional[datetime] = None
    updated_by_uuid: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["workflow_uuid", "filename", "materialized_source", "autogenerated_source", "is_overridden", "is_stale", "compiled_kind", "autogen_error", "warnings", "updated_at", "updated_by_uuid"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowWorkerSourceSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if filename (nullable) is None
        # and model_fields_set contains the field
        if self.filename is None and "filename" in self.model_fields_set:
            _dict['filename'] = None

        # set to None if materialized_source (nullable) is None
        # and model_fields_set contains the field
        if self.materialized_source is None and "materialized_source" in self.model_fields_set:
            _dict['materialized_source'] = None

        # set to None if autogenerated_source (nullable) is None
        # and model_fields_set contains the field
        if self.autogenerated_source is None and "autogenerated_source" in self.model_fields_set:
            _dict['autogenerated_source'] = None

        # set to None if compiled_kind (nullable) is None
        # and model_fields_set contains the field
        if self.compiled_kind is None and "compiled_kind" in self.model_fields_set:
            _dict['compiled_kind'] = None

        # set to None if autogen_error (nullable) is None
        # and model_fields_set contains the field
        if self.autogen_error is None and "autogen_error" in self.model_fields_set:
            _dict['autogen_error'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if updated_by_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.updated_by_uuid is None and "updated_by_uuid" in self.model_fields_set:
            _dict['updated_by_uuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowWorkerSourceSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workflow_uuid": obj.get("workflow_uuid"),
            "filename": obj.get("filename"),
            "materialized_source": obj.get("materialized_source"),
            "autogenerated_source": obj.get("autogenerated_source"),
            "is_overridden": obj.get("is_overridden") if obj.get("is_overridden") is not None else False,
            "is_stale": obj.get("is_stale") if obj.get("is_stale") is not None else False,
            "compiled_kind": obj.get("compiled_kind"),
            "autogen_error": obj.get("autogen_error"),
            "warnings": obj.get("warnings"),
            "updated_at": obj.get("updated_at"),
            "updated_by_uuid": obj.get("updated_by_uuid")
        })
        return _obj


