# coding: utf-8

"""
    Cyberwave API

    Cyberwave platform REST API. Use 'Bearer YOUR_TOKEN' for authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyberwave.rest.models.workflow_model_task_option_schema import WorkflowModelTaskOptionSchema
from cyberwave.rest.models.workflow_task_choice_schema import WorkflowTaskChoiceSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkflowModelTasksSchema(BaseModel):
    """
    WorkflowModelTasksSchema
    """ # noqa: E501
    node_updated_at: StrictStr
    model_updated_at: Optional[StrictStr]
    options: List[WorkflowModelTaskOptionSchema]
    catalog: Optional[List[WorkflowTaskChoiceSchema]] = None
    selection_issue: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["node_updated_at", "model_updated_at", "options", "catalog", "selection_issue"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowModelTasksSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in catalog (list)
        _items = []
        if self.catalog:
            for _item_catalog in self.catalog:
                if _item_catalog:
                    _items.append(_item_catalog.to_dict())
            _dict['catalog'] = _items
        # set to None if model_updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.model_updated_at is None and "model_updated_at" in self.model_fields_set:
            _dict['model_updated_at'] = None

        # set to None if selection_issue (nullable) is None
        # and model_fields_set contains the field
        if self.selection_issue is None and "selection_issue" in self.model_fields_set:
            _dict['selection_issue'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowModelTasksSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "node_updated_at": obj.get("node_updated_at"),
            "model_updated_at": obj.get("model_updated_at"),
            "options": [WorkflowModelTaskOptionSchema.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "catalog": [WorkflowTaskChoiceSchema.from_dict(_item) for _item in obj["catalog"]] if obj.get("catalog") is not None else None,
            "selection_issue": obj.get("selection_issue")
        })
        return _obj


